com.geonode.chloropleth/chloropleth/ElementarySchool/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import get_map,Grade,get_features,get_base_map
app_name= 'district'
urlpatterns = [
    url(r'^teachers$',get_map,{'feature':'ppteacher'},name="plot_ppteacher"),
    url(r'^students$',get_map,{'feature':'ppstudent'},name="plot_ppstudent"),
    url(r'^water$',Grade,name="plot_water"),
    url(r'^form$',get_features,name="get_feature"),
    url(r'^$',get_base_map,name="base_map"),
]

com.geonode.chloropleth/chloropleth/chloropleth/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^maharashtra/',include('ElementarySchool.urls')),
]

com.geonode.chloropleth/chloropleth/ElementarySchool/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.gis.db import models

# Create your models here.
class district_boundaries(models.Model):
    district_n = models.CharField(max_length=100, blank=True, null=True)
    district_c = models.CharField(max_length=3, blank=True, null=True)
    geom = models.MultiPolygonField(srid=4326, blank=True, null=True)

    def __str__(self):
        return self.district_n

class taluka_boundaries(models.Model):
    district_n = models.CharField(max_length=100)
    district_c = models.CharField(max_length=3)
    taluka_nam = models.CharField(max_length=50)
    taluka_cod = models.CharField(max_length=5)
    geom = models.MultiPolygonField(srid=4326)

    def __str__(self):
        return self.taluka_nam

class state_maharashtra(models.Model):
    st_nm = models.CharField(max_length=75)
    st_cen_cd = models.CharField(max_length=2)
    dt_cen_cd = models.CharField(max_length=2)
    district = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=4326)

    def __str__(self):
        return self.st_nm

class SchoolInfo(models.Model):
    txtbkyear = models.CharField(max_length=200, blank=True, null=True)
    workdays_hsec = models.CharField(max_length=200, blank=True, null=True)
    spltrg_place = models.CharField(max_length=200, blank=True, null=True)
    aad_f = models.CharField(max_length=200, blank=True, null=True)
    acstartmnth = models.CharField(max_length=200, blank=True, null=True)
    othrooms = models.CharField(max_length=200, blank=True, null=True)
    subexp_f = models.CharField(max_length=200, blank=True, null=True)
    cce_yn = models.CharField(max_length=200, blank=True, null=True)
    toiletwater_b = models.CharField(max_length=200, blank=True, null=True)
    edu_block = models.CharField(max_length=200, blank=True, null=True)
    up_comp_set_fre_textbookrec = models.CharField(max_length=200, blank=True, null=True)
    toiletwater_g = models.CharField(max_length=200, blank=True, null=True)
    clgoods = models.CharField(max_length=200, blank=True, null=True)
    subexp_m = models.CharField(max_length=200, blank=True, null=True)
    par_in_pos_sec = models.CharField(max_length=200, blank=True, null=True)
    clsunderconst = models.CharField(max_length=200, blank=True, null=True)
    handwash_yn = models.CharField(max_length=200, blank=True, null=True)
    totcomp_func = models.CharField(max_length=200, blank=True, null=True)
    acname = models.CharField(max_length=200, blank=True, null=True)
    yearrecog = models.CharField(max_length=200, blank=True, null=True)
    schmgths = models.CharField(max_length=200, blank=True, null=True)
    smg_e = models.CharField(max_length=200, blank=True, null=True)
    meds1 = models.CharField(max_length=200, blank=True, null=True)
    latsec = models.CharField(max_length=200, blank=True, null=True)
    meds4 = models.CharField(max_length=200, blank=True, null=True)
    pcr_shared = models.CharField(max_length=200, blank=True, null=True)
    sec_resi_school_yn = models.CharField(max_length=200, blank=True, null=True)
    p_playmat_av = models.CharField(max_length=200, blank=True, null=True)
    toiletg_func = models.CharField(max_length=200, blank=True, null=True)
    spltrg_totev = models.CharField(max_length=200, blank=True, null=True)
    londeg = models.CharField(max_length=200, blank=True, null=True)
    smg_r = models.CharField(max_length=200, blank=True, null=True)
    spltrg_py_enrolled_b = models.CharField(max_length=200, blank=True, null=True)
    txtbkmnth = models.CharField(max_length=200, blank=True, null=True)
    sch_category = models.CharField(max_length=200, blank=True, null=True)
    schhrschild_upr = models.CharField(max_length=200, blank=True, null=True)
    clmajors = models.CharField(max_length=200, blank=True, null=True)
    clminorhs = models.CharField(max_length=200, blank=True, null=True)
    urinals_b = models.CharField(max_length=200, blank=True, null=True)
    toilet_g = models.CharField(max_length=200, blank=True, null=True)
    workdays_sec = models.CharField(max_length=200, blank=True, null=True)
    smc_yn = models.CharField(max_length=200, blank=True, null=True)
    boardhsec = models.CharField(max_length=200, blank=True, null=True)
    ebmc_m = models.CharField(max_length=200, blank=True, null=True)
    lang1 = models.CharField(max_length=200, blank=True, null=True)
    spltrg_material_yn = models.CharField(max_length=200, blank=True, null=True)
    lang3 = models.CharField(max_length=200, blank=True, null=True)
    lang2 = models.CharField(max_length=200, blank=True, null=True)
    workdays_upr = models.CharField(max_length=200, blank=True, null=True)
    furntch = models.CharField(max_length=200, blank=True, null=True)
    spltrg_by = models.CharField(max_length=200, blank=True, null=True)
    clgood = models.CharField(max_length=200, blank=True, null=True)
    clmajor_tnt = models.CharField(max_length=200, blank=True, null=True)
    bookbank_yn = models.CharField(max_length=200, blank=True, null=True)
    bankname = models.CharField(max_length=200, blank=True, null=True)
    reg_in_pos_hsec = models.CharField(max_length=200, blank=True, null=True)
    clgood_tnt = models.CharField(max_length=200, blank=True, null=True)
    water = models.CharField(max_length=200, blank=True, null=True)
    toiletb_func = models.CharField(max_length=200, blank=True, null=True)
    schhrschild_pr = models.CharField(max_length=200, blank=True, null=True)
    handrails = models.CharField(max_length=200, blank=True, null=True)
    anganwadi_yn = models.CharField(max_length=200, blank=True, null=True)
    medh4 = models.CharField(max_length=200, blank=True, null=True)
    medh3 = models.CharField(max_length=200, blank=True, null=True)
    medh2 = models.CharField(max_length=200, blank=True, null=True)
    medh1 = models.CharField(max_length=200, blank=True, null=True)
    spltrg_cy_provided_b = models.CharField(max_length=200, blank=True, null=True)
    totcls11 = models.CharField(max_length=200, blank=True, null=True)
    totcls12 = models.CharField(max_length=200, blank=True, null=True)
    spltrg_py_provided_b = models.CharField(max_length=200, blank=True, null=True)
    assembly_constituency = models.CharField(max_length=200, blank=True, null=True)
    spltrg_cy_provided_g = models.CharField(max_length=200, blank=True, null=True)
    spltrg_py_provided_g = models.CharField(max_length=200, blank=True, null=True)
    ac_yn = models.CharField(max_length=200, blank=True, null=True)
    relminority_type = models.CharField(max_length=200, blank=True, null=True)
    municipality = models.CharField(max_length=200, blank=True, null=True)
    conti_e = models.CharField(max_length=200, blank=True, null=True)
    toiletb = models.CharField(max_length=200, blank=True, null=True)
    bankac_yn = models.CharField(max_length=200, blank=True, null=True)
    toiletd = models.CharField(max_length=200, blank=True, null=True)
    estdyear = models.CharField(max_length=200, blank=True, null=True)
    conti_r = models.CharField(max_length=200, blank=True, null=True)
    ptameeting = models.CharField(max_length=200, blank=True, null=True)
    statname = models.CharField(max_length=200, blank=True, null=True)
    txtbkrecd_yn = models.CharField(max_length=200, blank=True, null=True)
    lowclass = models.CharField(max_length=200, blank=True, null=True)
    website = models.CharField(max_length=200, blank=True, null=True)
    scst_f = models.CharField(max_length=200, blank=True, null=True)
    clmajor = models.CharField(max_length=200, blank=True, null=True)
    clsuconst12 = models.CharField(max_length=200, blank=True, null=True)
    furn_yn10 = models.CharField(max_length=200, blank=True, null=True)
    clsuconst10 = models.CharField(max_length=200, blank=True, null=True)
    clsuconst11 = models.CharField(max_length=200, blank=True, null=True)
    scst_m = models.CharField(max_length=200, blank=True, null=True)
    clminor_kuc = models.CharField(max_length=200, blank=True, null=True)
    smcbankac_yn = models.CharField(max_length=200, blank=True, null=True)
    spltrg_py_enrolled_g = models.CharField(max_length=200, blank=True, null=True)
    smcmem_f = models.CharField(max_length=200, blank=True, null=True)
    clmajorhs = models.CharField(max_length=200, blank=True, null=True)
    village = models.CharField(max_length=200, blank=True, null=True)
    pri_resi_school_yn = models.CharField(max_length=200, blank=True, null=True)
    rampsneeded_yn = models.CharField(max_length=200, blank=True, null=True)
    smcmem_m = models.CharField(max_length=200, blank=True, null=True)
    anganwadi_tch = models.CharField(max_length=200, blank=True, null=True)
    visitscrc = models.CharField(max_length=200, blank=True, null=True)
    sip_yn = models.CharField(max_length=200, blank=True, null=True)
    deo_m = models.CharField(max_length=200, blank=True, null=True)
    ramps_yn = models.CharField(max_length=200, blank=True, null=True)
    osrc_e = models.CharField(max_length=200, blank=True, null=True)
    totcls10 = models.CharField(max_length=200, blank=True, null=True)
    ifsc = models.CharField(max_length=200, blank=True, null=True)
    cityname = models.CharField(max_length=200, blank=True, null=True)
    campusplan_yn = models.CharField(max_length=200, blank=True, null=True)
    distu = models.CharField(max_length=200, blank=True, null=True)
    block_name = models.CharField(max_length=200, blank=True, null=True)
    aidrecd = models.CharField(max_length=200, blank=True, null=True)
    dists = models.CharField(max_length=200, blank=True, null=True)
    ppstudent = models.IntegerField(blank=True, null=True)
    up_palymat_av = models.CharField(max_length=200, blank=True, null=True)
    spltrg_evtrnd = models.CharField(max_length=200, blank=True, null=True)
    p_tle_av = models.CharField(max_length=200, blank=True, null=True)

com.geonode.chloropleth/chloropleth/ElementarySchool/forms.py
from django import forms
from .models import state_maharashtra

class AttributeForm(forms.Form):
    level = (
        ('district','District'),
        ('taluka','Taluka'),
    )

    district = tuple([(i['district'],i['district']) for i in state_maharashtra.objects.values('district').all()])
    feature = (
        ('ppteacher','Teacher'),
        ('water','Water'),
        ('ppstudent','Student'),
    )

    get_level = forms.ChoiceField(label='Level',choices=level,initial='district')
    get_district = forms.ChoiceField(label='District',choices=district,disabled=True)
    get_feature = forms.ChoiceField(label='Feature',choices = feature)

com.geonode.chloropleth/chloropleth/ElementarySchool/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render_to_response,HttpResponse,Http404,HttpResponseRedirect,render
from .models import district_boundaries,taluka_boundaries,state_maharashtra,SchoolInfo
from django.core.serializers import serialize
from colour import Color
from django.db.models import Count,Sum
from .forms import AttributeForm
import json


def get_base_map(request):
    district = state_maharashtra.objects.all().order_by('district')
    # serialize the data
    district_serialize = serialize('geojson', district,
                                   geometry_field='geom',
                                   fields=('district',))
    dist_json = json.loads(district_serialize)
    # remove crs field
    dist_json.pop('crs', None)
    district = json.dumps(dist_json)

    return render_to_response('chloropleth/maps.html', {'district': district,'name':"Base Map"})


# Create your views here.
def get_map(request,feature):
    district = state_maharashtra.objects.all().order_by('district')

    #serialize the data
    district_serialize = serialize('geojson', district,
          geometry_field='geom',
          fields=('district',))

    #create a dictionary
    max_v = 0
    min_v = 1000
    dist_json = json.loads(district_serialize)
    # remove crs field
    dist_json.pop('crs',None)
    for i in range(len(district)):
        d_name = dist_json['features'][i]['properties']['district']
        features = SchoolInfo.objects.values(str(feature)).filter(distname__iexact = d_name).aggregate(Sum(str(feature)))

        if(min_v > features[str(feature)+'__sum']):
            min_v = features[str(feature)+'__sum']
        if (max_v < features[str(feature) + '__sum']):
            max_v = features[str(feature) + '__sum']

        rag = max_v - min_v

        dist_json['features'][i]['properties']['feature_val'] = features[str(feature)+'__sum']
    district = json.dumps(dist_json)

    grade = [round(float(i*rag)/100,2) for i in range(0,110,20)]
    color_list = list(str(i) for i in Color('yellow').range_to(Color('red'), len(grade)))
    return render_to_response('chloropleth/maps.html',{'district':district,'Name':str(feature),'range':rag,
                                                       'grade':grade,'color':color_list})

def Grade(request):

    try:
        from colour import Color
        dark_blue = Color('darkblue')
        light_blue = Color('lightblue')
        color_list = list(str(i) for i in light_blue.range_to(dark_blue,5))

        #Get districts shape
        district = state_maharashtra.objects.all().order_by('district')

        # serialize the data
        district_serialize = serialize('geojson', district,
                                       geometry_field='geom',
                                       fields=('district',))
        # create a dictionary
        dist_json = json.loads(district_serialize)

        # remove crs field
        dist_json.pop('crs', None)

        max_v = 0
        min_v = 1000
        weights = ['', 0, 0, 0, 1, 0]

        for i in range(len(district)):
            d_name = dist_json['features'][i]['properties']['district']
            water_info = SchoolInfo.objects.values('water').annotate(Count('water')).filter(distname__iexact=d_name).order_by('water')

            weighted_values = list()
            for x in water_info:
                if (x.get('water')) is not None:
                    if (int(x.get('water')) == 9):
                        continue
                weighted_values.append(round(weights[int(x.get('water'))] * x.get('water__count'),3))
                temp = round(sum(weighted_values) / len(weighted_values),2)
                if (temp>max_v):
                    max_v = temp
                if (temp<min_v):
                    min_v = temp
            dist_json['features'][i]['properties']['water'] = temp
        district = json.dumps(dist_json)
        range_value = max_v - min_v
        return render_to_response('chloropleth/water.html', {'district': district, 'Name': "Water Quality",'range':range_value,'color':color_list })

    except IndexError ,e:
        raise Http404("Nope")


def get_features(request):
    form = AttributeForm()
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = AttributeForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            print form.cleaned_data
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = AttributeForm()

    return render(request,'chloropleth/form.html',{'form':form})

com.geonode.chloropleth/chloropleth/ElementarySchool/templates/chloropleth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta cfharset="UTF-8">
    <title>{% block title %}{% endblock  %}</title>

    <link rel="stylesheet" href="{% static '/maps/leaflet.css' %}" />
    <script src="{% static '/maps/leaflet.js' %}"></script>
</head>
<body>
{% block form %}

{% endblock %}
{% block map %}

{% endblock %}
</body>
</html>

com.geonode.chloropleth/chloropleth/ElementarySchool/templates/chloropleth/form.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Chloropleth Maps {% endblock %}</title>
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'maps/bootstrap.min.css' %}">
    <script src="{% static 'maps/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'maps/bootstrap.min.js' %}"></script>

    <style>
.loader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #3498db;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
}

/* Safari */
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>

</head>
<body>

    {% block form %}
<form method="post" id="f1" class="form-group" action="{% url 'district:get_feature' %}">
    {% csrf_token %}
        {{ form.get_level|add_class:" form-control " }}
        {{ form.get_district| add_class:" form-control "}}
        {{ form.get_feature | add_class:" form-control "}}
    <input type="submit" value="Go!!">
</form>
    <div class="container">
    <div class="embed-responsive embed-responsive-16by9">
     <iframe src="#" name="chloropleth_map_container" id="ifrm"
             class="embed-responsive-item"  width="1050" height="600"
             style="-webkit-transform:scale(0.9);-mz-transform-scale(0.9);"
     >
    </iframe>
    </div>

</div>
    <script>
        $(document).on(
        'change','#id_get_level',
        function(e){
        if($('#id_get_level').val()=='taluka'){
            $('#id_get_district').prop( "disabled", false );
        }
        else
        {
            $('#id_get_district').prop("disabled", true);
        }})

        $(document).on('submit','#f1',
        function(e){
            e.preventDefault();
            if($('#id_get_level').val()=='district'){
                if($('#id_get_feature').val()=='water'){
                $('#ifrm').prop("src","{% url 'district:plot_water' %}");
                }
                if($('#id_get_feature').val()=='ppteacher'){
                $('#ifrm').prop("src","{% url 'district:plot_ppteacher' %}");
                }
                 if($('#id_get_feature').val()=='ppstudent'){
                $('#ifrm').prop("src","{% url 'district:plot_ppstudent' %}");
                }
            }
        });

    </script>
    {% endblock %}
</body>

com.geonode.chloropleth/chloropleth/ElementarySchool/templates/chloropleth/maps.html
{% extends 'chloropleth/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Chloropleth Maps {% endblock %}</title>
        <link rel="styleseet" href="{% static '/maps/leaflet.css' %}" />
    <script src="{% static '/maps/leaflet.js' %}"></script>
    <style>

        #map {height:100%;width:100%};
        .info {
        padding: 6px 8px;
        font: 14px/16px Arial, Helvetica, sans-serif;
        background: white;
        background: rgba(255,255,255,0.8);
        box-shadow: 0 0 15px rgba(0,0,0,0.2);
        border-radius: 5px;
        }

.info h4 {
    margin: 0 0 5px;
    color: #777;
}
    .loader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #3498db;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
}

/* Safari */
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>

</head>
<body style="height:100%; width:100%;">
<h1>Maharashtra</h1>
{% block map %}
<div class="loader"></div>
<div id="map" style="height:600px;width:1024px">

</div>

<script>
    var dist_layer;

    /*GeoJson layer*/
    var data = {{district|safe}};
      /*create a new map and assign it to a variable 'map'*/
    var map = L.map('map').setView([18.97,75.86],7); /* center point and zoom level setView([x_cen, y_cen], 4);*/

// control that shows state info on hover
	var info = L.control();

	info.onAdd = function (map) {
		this._div = L.DomUtil.create('div', 'info');
		this.update();
		return this._div;
	};

	info.update = function (props) {
		this._div.innerHTML = '<h4>{{Name|upper}}</h4>' +  (props ?
			'<b>' + props.district + '</b><br />' + props.feature_val +' {{Name}}'
			: 'Hover over a state');
	};

	info.addTo(map);

    range = {{ range }};
    grade ={{ grade|safe }};
    color = {{ color|safe }};
	// get color depending on population density value
	function getColor(d) {

		for(i=0;i<color.length-1;i++)
		{
		    if(d<grade[i])
		    {
		        return color[i];
		    }
		}
				return color[i];
	}

	function style(feature) {
		return {
			weight: 2,
			opacity: 1,
			color: 'white',
			dashArray: '3',
			fillOpacity: 0.7,
			fillColor: getColor(feature.properties.feature_val)
		};
	}

	function highlightFeature(e) {
		var layer = e.target;

		layer.setStyle({
			weight: 5,
			color: '#666',
			dashArray: '',
			fillOpacity: 0.7
		});

		if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
			layer.bringToFront();
		}

		info.update(layer.feature.properties);
	}

	var geojson;

	function resetHighlight(e) {
		geojson.resetStyle(e.target);
		info.update();
	}

	function zoomToFeature(e) {
		map.fitBounds(e.target.getBounds());
	}

	function onEachFeature(feature, layer) {
		layer.on({
			mouseover: highlightFeature,
			mouseout: resetHighlight,
			click: zoomToFeature
		});
	}

	geojson = L.geoJson(data, {
		style: style,
		onEachFeature: onEachFeature
	}).addTo(map);

	map.attributionControl.addAttribution('Teacher data &copy; <a href="http://census.gov/">UDISE</a>');

var legend = L.control({position: 'bottomright'});

legend.onAdd = function (map) {

    var div = L.DomUtil.create('div', 'info legend'),
        grades = {{grade|safe}};
        labels = [];

    // loop through our density intervals and generate a label with a colored square for each interval
    for (var i = 0; i < grades.length; i++) {
        div.innerHTML +=
            '<span style="width:5px;background:' + getColor(grades[i] + 1) + '"></span> ' +
            grades[i] + (grades[i + 1] ? '&ndash;' + grades[i + 1] + '<br>' : '+');
    }

    return div;
};
legend.addTo(map);



</script>
{% endblock %}</body>
<style>

</style>
</html>

com.geonode.chloropleth/chloropleth/ElementarySchool/templates/chloropleth/water.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>{% extends 'chloropleth/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Chloropleth Maps {% endblock %}</title>
        <link rel="styleseet" href="{% static '/maps/leaflet.css' %}" />
    <script src="{% static '/maps/leaflet.js' %}"></script>
    <style>

        #map {height:350px};
        .info {
        padding: 6px 8px;
        font: 14px/16px Arial, Helvetica, sans-serif;
        background: white;
        background: rgba(255,255,255,0.8);
        box-shadow: 0 0 15px rgba(0,0,0,0.2);
        border-radius: 5px;
        }

.info h4 {
    margin: 0 0 5px;
    color: #777;
}
    </style>
</head>
<body>
<h1>Maharashtra</h1>
{% block map %}
<div id="map" style="height:750px;width:1024px"></div>

<script>
    var dist_layer;

    /*GeoJson layer*/
    var data = {{district|safe}}
      /*create a new map and assign it to a variable 'map'*/
    var map = L.map('map').setView([18.97,75.86],7); /* center point and zoom level setView([x_cen, y_cen], 4);*/

// control that shows state info on hover
	var info = L.control();

	info.onAdd = function (map) {
		this._div = L.DomUtil.create('div', 'info');
		this.update();
		return this._div;
	};

	info.update = function (props) {
		this._div.innerHTML = '<h4>{{Name|upper}}</h4>' +  (props ?
			'<b>' + props.district + '</b><br />' + props.water + ' Water Quality Index'
			: 'Hover over a state');
	};

	info.addTo(map);


	// get color depending on population density value
	range = {{ range }};
	colors = {{ color|safe }};
	function getColor(d) {
		return d < range * 20 / 100 ? colors[0]:
               d < range * 40 / 100 ? colors[1]:
               d < range * 60 / 100 ? colors[2]:
               d < range * 80 / 100 ? colors[3]:
                                            colors[4];
	}

	function style(feature) {
		return {
			weight: 1,
			opacity: 1,
			color: 'white',
			dashArray: '4',
			fillOpacity: 0.7,
			fillColor: getColor(feature.properties.water)
		};
	}

	function highlightFeature(e) {
		var layer = e.target;

		layer.setStyle({
			weight: 2,
			color: 'black',
			dashArray: '',
			fillOpacity: 0.7
		});

		if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
			layer.bringToFront();
		}

		info.update(layer.feature.properties);
	}

	var geojson;

	function resetHighlight(e) {
		geojson.resetStyle(e.target);
		info.update();
	}

	function zoomToFeature(e) {
		map.fitBounds(e.target.getBounds());
	}

	function onEachFeature(feature, layer) {
		layer.on({
			mouseover: highlightFeature,
			mouseout: resetHighlight,
			click: zoomToFeature
		});
	}

	geojson = L.geoJson(data, {
		style: style,
		onEachFeature: onEachFeature
	}).addTo(map);

	map.attributionControl.addAttribution('Water Quality &copy; <a href="http://census.gov/">UDISE</a>');


	var legend = L.control({position: 'bottomright'});

	legend.onAdd = function (map) {

		var div = L.DomUtil.create('div', 'info legend'),
			grades = [0,100, 200, 500, 1000, 1500, 2000, 5000],
			labels = [],
			from, to;

		for (var i = 0; i < grades.length; i++) {
			from = grades[i];
			to = grades[i + 1];

			labels.push(
				'<i style="background:' + getColor(from + 1) + '"></i> ' +
				from + (to ? '&ndash;' + to : '+'));
		}

		div.innerHTML = labels.join('<br>');
		return div;
	};

	legend.addTo(map);
</script>
{% endblock %}</body>
<style>

</style>
</html>